apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.webport }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.dlnaport }}
      targetPort: dlna
      protocol: UDP
      name: dlna
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
